spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password:
  jpa:
    database-plataform: org.hibernate.dialect.H2Dalect
  h2:
    console:
      enabled: true
      path: /h2-console
